### ISSUE TITLE
Public/Private mode

### ISSUE THREAD

**Issue by mouzzampk2014** [thelounge/thelounge-docker#102]
Hi, I am trying to use Private mode so I can keep my channels save. In Public mode all channels remove after closing the page. 

Do I need to change the public value from true to false inside config.json or is there any environment variable I can use to change? Thank you

// This value is set to `false` by default.
	`public: true,`

**Comment by MiniDigger** [comment]
Yes, the config is made to be edited.

**Comment by mouzzampk2014** [comment]
Thank you so much. I also noticed pi interface is set to public and if I run thelounge on ubuntu then interface set to private.
