### ISSUE TITLE
Shuts off on its own

### ISSUE THREAD

**Issue by minidarknova** [thelounge/thelounge-docker#118]
Hi there,
I am using the docker and every few days, it autocmatically shuts off on its own and I have to use compose to get it back on and start it again. 
What is going on??
Only this docker does this and nothing else do the same. Using Dockstarter script.

**Comment by brunnre8** [comment]
Check the logs. the lounge certainly doesn't do that on its own so chances are this is a misconfiguration with your docker setup.

What do you use to start the containers? Systemd? Docker itself?

Do you have some auto updater running that messes with containers automagically?

**Comment by minidarknova** [comment]
I am using DockSTARTer .com script since I am newbie with linux. I have 25 dockers running on my server. None will crash or stop itself except this one. only thing I have changed is the network so it would go through my OpenVPN docker. Which also supplies another docker (JDownloader 2) with no issue on that.
 ouroboros is also running, but I doubt that is the issue.

**Comment by brunnre8** [comment]
don't guess, look at the logs

**Comment by minidarknova** [comment]
Is there somewhere that I can turn on Logging?

**Comment by brunnre8** [comment]
Chances are logging os already turned on https://docs.docker.com/config/containers/logging/

Your fancy dockerstarter thingy installs 2 auto updaters, check those first. Then docker compose and if all else fails the logs of TL itself (but I can tell you that TL certainly does not restart willy nilly)

**Comment by minidarknova** [comment]
But why out of 25 (- 2 or 3 for portainer and ouroboros) only this docker quits for literally no reasons. And everything is working with no issue? The rest should also get updated, right? Jellyfin, sonarr,raddar, etc...      
and if I cannot find it in portainer once it goes off, can I still find the logs for it through using `docker logs thelounge` ?

**Comment by brunnre8** [comment]
it's your setup, you tell me.

**Comment by williamboman** [comment]
Dockstarter.com seems to be using a [different image](https://hub.docker.com/r/linuxserver/thelounge)
