### ISSUE TITLE
Error loading node-sqlite3 on ARM (raspberry pi 4) using alpine 

### ISSUE THREAD

**Issue by Dav1dde** [thelounge/thelounge-docker#126]
Using the 4.3.0-pre.6-alpine container on ARM shows the following error when starting:

```
[ERROR] Unable to load node-sqlite3 module. See https://github.com/mapbox/node-sqlite3/wiki/Binaries
```

Version/sha:
```
Containers:
  thelounge:
    Image:         thelounge/thelounge:4.3.0-pre.6-alpine
    Image ID:      docker.io/thelounge/thelounge@sha256:1212278dc9de1f25d2e7cdc8c4a62995fe62c96b3440cabbcd68e04b71a543bd
```

EDIT: Same Issue in 4.3.0-alpine

**Comment by mhajder** [comment]
I have the same error on ARM instance for the thelounge:latest image (version 4.3.0).

**Comment by williamboman** [comment]
Hello! Does any of the pre releases or release candidates work? What's the latest version that works?

**Comment by mhajder** [comment]
> Hello! Does any of the pre releases or release candidates work? What's the latest version that works?

Surely everything works fine for thelounge:4.2.0. It looks more like they broke node-sqlite3 again.

**Comment by Dav1dde** [comment]
@williamboman pre-1 does not have the error when starting, pre-{2,3,4} can't be started (there is no ARM image for these pre releases)

**Comment by williamboman** [comment]
So I've been experimenting a bit (#131) and I think it's gucci now. I pushed some builds to [williamboman/thelounge](https://hub.docker.com/repository/docker/williamboman/thelounge/tags), please give em a try.

**Comment by williamboman** [comment]
Just doing some last analysis of the image layers to justify the increase in image size

**Comment by Dav1dde** [comment]
Looks good, the error is gone, I assume sqlite is also working:

```
lithium :: ~ » sudo kubectl create deployment tmp1 --image=williamboman/thelounge:4.3.0-alpine -n tmp
lithium :: ~ » sudo kubectl logs tmp1-66868cf6d6-xcmjj -n tmp
2021-11-23 20:42:39 [INFO] Configuration file created at /var/opt/thelounge/config.js.
2021-11-23 20:42:41 [INFO] The Lounge v4.3.0 (Node.js 16.13.0 on linux arm64)
2021-11-23 20:42:41 [INFO] Configuration file: /var/opt/thelounge/config.js
2021-11-23 20:42:41 [INFO] Available at http://[::]:9000/ in private mode
2021-11-23 20:42:41 [INFO] New VAPID key pair has been generated for use with push subscription.
2021-11-23 20:42:41 [INFO] There are currently no users. Create one with thelounge add <name>.
```

**Comment by mhajder** [comment]
Everything works. Thanks!
