### ISSUE TITLE
identd

### ISSUE THREAD

**Issue by daomengRen** [thelounge/thelounge-docker#137]
How can I configure identd in config.js when I add `--publish 113:9001` to run the container, 
currently the configuration is as follows:
`	identd: {
		enable: true,
		port: 113,
	},`
Should I still configure according to this, 
[https://thelounge.chat/docs/guides/identd-and-oidentd#using-oidentd-to-forward-requests-to-the-built-in-server](url)

**Comment by brunnre8** [comment]
This is a bug tracker and not a support forum, please use IRC if you have setup questions.
We're on libera under #thelounge and there's a docker chan as well.
