### ISSUE TITLE
TL gets a SIGTERM/SIGINT roughly every 5min

### ISSUE THREAD

**Issue by the-lazy-fox** [thelounge/thelounge-docker#140]
Dear all,

Since I’ve updated my container with the latest version (fa1e23a78a7a) this morning 6am CEST, I’m constantly disconnected and reconnected. It also seems to disconnect and reconnect me when opening thelounge through my reverse proxy.
Could you please let me know if you have a similar issue?
How to fix this?

Thank you!

**Comment by the-lazy-fox** [comment]
Any updates? Thank you!

**Comment by the-lazy-fox** [comment]
Updated to latest and still having the issue :(

**Comment by williamboman** [comment]
Hey @the-lazy-fox, I'm fairly certain this is not any behavior that is intrinsic to the image itself. Do you use any thelounge plugins or use any other software to manage containers (k8s, docker swarm, watchtower, etc)? Have you perhaps gathered any other intel in terms of reproducing this?

**Comment by the-lazy-fox** [comment]
Hello @williamboman 
My TheLounge container is used through a wireguard container and as watchtower and deunhealth on it. It works perfectly with the 4.3.0 but with the latest, it restarts exactly every 5 minutes.

**Comment by williamboman** [comment]
And does this happen if you run the container by itself, not hooked up to either Watchtower or Deunhealth?

**Comment by the-lazy-fox** [comment]
And that's it... thank you for suggesting this. I don't know why I didn't check that before.
It seems the container is not containing curl anymore so my healthcheck is failing and deunhealth was restarting it...
Any reasons why removing curl?

**Comment by brunnre8** [comment]
easy enough, TL doesn't need it and hence you don't have curl in the container.

**Comment by williamboman** [comment]
> Any reasons why removing curl?

A more thorough answer would be that starting with `4.3.1`, only alpine images are distributed via `thelounge/thelounge`. Previously the default images would be based off of a Debian Bullseye image (which comes bootstrapped with a bunch of utilities installed, curl for example). Alpine images help reduce the overall footprint of images by only including the things necessary to run the container. I wouldn't be opposed to including a subset of these auxiliary tools if it helps people manage their environment, curl adds about `~1.8MB`.

I've never used Deunhealth before, and when looking at their source I can't find any traces of `curl`? Or is this a healthcheck that you've specified yourself via Docker's `HEALTHCHECK` directive?

**Comment by brunnre8** [comment]
>I wouldn't be opposed to including a subset of these auxiliary tools if it helps people manage their environment

Adding extra deps not actually related to TL for a health check internal to the container sounds strange to me...
Would it not be easier to do the ping with some other monitoring container?
docker containers should do one thing only, provide the service no?

TIL healthcheck directive.

We have node in the container, should be trivial to avoid curl

**Comment by the-lazy-fox** [comment]
> > Any reasons why removing curl?
> 
> A more thorough answer would be that starting with `4.3.1`, only alpine images are distributed via `thelounge/thelounge`. Previously the default images would be based off of a Debian Bullseye image (which comes bootstrapped with a bunch of utilities installed, curl for example). Alpine images help reduce the overall footprint of images by only including the things necessary to run the container. I wouldn't be opposed to including a subset of these auxiliary tools if it helps people manage their environment, curl adds about `~1.8MB`.
> 
> I've never used Deunhealth before, and when looking at their source I can't find any traces of `curl`? Or is this a healthcheck that you've specified yourself via Docker's `HEALTHCHECK` directive?

Deunhealth find unhealthy containers and restart them. It was restarting my TL container because considered as unhealthy. Why?

As the container doesn't come with an embedded Healthcheck, I've added one myself to ensure the container is running through my VPN by pinging it's internal IP (through the VPN in the same stack).

I've updated the image, curl disappeared as you rebased to Alpine (I understand the motivation 💯% ) so my healthcheck was always failing! I didn't think about looking there.

I've replaced it with a wget query now 👍🏼 

It would be a good thing to integrate directly a Healthcheck in the container!
