### ISSUE TITLE
Not complete docker-compose file

### ISSUE THREAD

**Issue by p6002** [thelounge/thelounge-docker#147]
How i can add user and password to docker compose?

**Comment by brunnre8** [comment]
by using the docker commands indicated in the readme

**Comment by p6002** [comment]
To docker compose file, i dont want to run any commands on my server, just deploy docker container.

**Comment by brunnre8** [comment]
TL isn't a 12 factor app, it's stateful.
You may not like it, but that's the way it works currently.
