### ISSUE TITLE
Not longer stayed logged in. 

### ISSUE THREAD

**Issue by VinneyUK** [thelounge/thelounge-docker#155]
Hi, 
pulling my hair out why the client will no longer stay logged in, after I close the browser? 

The is my docker compose 

Any ideas, please?

`---
version: "2.1"
services:
  thelounge:
    image: lscr.io/linuxserver/thelounge:latest
    container_name: thelounge
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /home/dietpi/thelounge:/config
    ports:
      - 9000:9000
    restart: unless-stopped`

**Comment by brunnre8** [comment]
This isn't our image, so wrong tracker > lscr.io/linuxserver/thelounge:latest

Else are you sure you config.js says public: false?
Hop into #thelounge on libera and we can debug this
