### ISSUE TITLE
Receive file transfers (e.g. cctp/xdcc)

### ISSUE THREAD

**Issue by MrScripter85** [thelounge/thelounge-docker#160]
Hello, how to enable TheLounge to receive file transfers via IRC?

Thanks!

**Comment by fnutt** [comment]
This is not implemented in The Lounge. It has been discussed in lenght before and the conclusion has always been to not implement it.

It may however, in the far future, be a plugin if someone codes it.

**Comment by brunnre8** [comment]
This is an issue tracker for the container too...

Use our IRC channel on libera for those kinds of questions
