### ISSUE TITLE
can't use add command to add user to the container

### ISSUE THREAD

**Issue by fhazal** [thelounge/thelounge-docker#180]
`docker exec --user node -it thelounge thelounge add MyUser`

i try to run the command above but docker give me `error: unknown command 'add'`

my os : Ubuntu 22.04 

docker version :

```
Client: Docker Engine - Community
 Version:           24.0.7
 API version:       1.43
 Go version:        go1.20.10
 Git commit:        afdd53b
 Built:             Thu Oct 26 09:07:41 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          24.0.7
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.10
  Git commit:       311b9ff
  Built:            Thu Oct 26 09:07:41 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.24
  GitCommit:        61f9fd88f79f081d64d6fa3bb1a0dc71ec870523
 runc:
  Version:          1.1.9
  GitCommit:        v1.1.9-0-gccaecfc
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

```

please advise.

**Comment by fhazal** [comment]
docker exec --user node -it thelounge thelounge
Usage: thelounge [options] [command]

Options:
  -v, --version             output the version number
  -c, --config <key=value>  override entries of the configuration file, must be specified for each entry that needs to be overriden
  -h, --help                display help for command

Commands:
  start [options]           Start the server
  install <package>         Install a theme or a package
  uninstall <package>       Uninstall a theme or a package
  upgrade [packages...]     Upgrade installed themes and packages to their latest versions
  outdated                  Check for any outdated packages
  help [command]            display help for command

Environment variable:
  THELOUNGE_HOME            Path for all configuration files and folders. Defaults to /home/node/.thelounge

root@bajubesiKVM:~/proxy_manager# docker exec --user node -it thelounge thelounge -v
v4.4.1
root@bajubesiKVM:~/proxy_manager#

ghcr.io/thelounge/thelounge   latest    d04035cbd24b   13 days ago    220MB

this all the response i get for all the command u give me.

**Comment by miniksa** [comment]
I just had this problem and figured it out. 

https://github.com/thelounge/thelounge/blob/0d9c184f19dd26fc9bc7e7c8b112e02c5261fe71/server/command-line/index.ts#L47-L53

The user commands are not loaded into the module if the server is set to `public: true` in the `config.js`.... which it seems to be by default when you start a fresh container now.

So turn off the container, go get the `config.js` file and set `public: false`, then load it back in and restart the container. Then the user commands will be available.
