### ISSUE TITLE
Private mode: Authentication Failed

### ISSUE THREAD

**Issue by Oleekae** [thelounge/thelounge-docker#182]
ok, just found on a page that has nothing to do with The Lounge, a pity that this essential information is not provided in the first instance.

**Comment by brunnre8** [comment]
>I used the following repository to install it on my synology: lscr.io/linuxserver/thelounge

You weren't even using our container...
For ours we do document it quite obviously in the readme as well though https://github.com/thelounge/thelounge-docker?tab=readme-ov-file#adding-users

So not quite sure where you tried looking for the information if not in the obvious place.

**Comment by Oleekae** [comment]
> You weren't even using our container... For ours we do document it quite obviously in the readme as well though https://github.com/thelounge/thelounge-docker?tab=readme-ov-file#adding-users
> 
> So not quite sure where you tried looking for the information if not in the obvious place.

well, I had not seen this section of yours, even if it is not your repository that I installed, it is still in substance your absolute creation and development. I thank you for taking me to the right section to be able to explore the different settings of the repository.
