### ISSUE TITLE
Ability to send messages to lobbies

### ISSUE THREAD

**Issue by fl0wfr** [thelounge/thelounge-docker#191]
Hi,
I'm facing an issue with TheLounge, I'm connecting to an IRC server which requires to send an authentication message to the lobby. But TheLounge returns the following error: "Messages can not be sent to lobbies.". Would it be possible to allow this feature?
Thanks,

**Comment by Jay2k1** [comment]
The "lobby" is not a room or anything else that is a valid recipient, so you cannot send anything. You probably want to send a server command, so try using `/quote <your command`, e.g. `/quote authenticate myuser mypass` or whatever your network expects.

**Comment by fl0wfr** [comment]
Hi @Jay2k1 ,

The command is /msg <name of the lobby> .invite <pass> #channel1 #channel2 #channel3

**Comment by fl0wfr** [comment]
/msg is expecting a channel as argument, in my case it's a direct message to a user with the same name as the IRC server.
I tried /quote which is simply ignored (not run, and no error).

**Comment by Jay2k1** [comment]
Not quite, `/msg` expects a *target*, that can be a channel or a user. If I do `/msg .invite test` in a server lobby, I get 
`User .invite hasn't logged in or does not exist.`
Are you sure you prefix the command with a slash?

**Comment by fl0wfr** [comment]
Yes, and the target has the same name as the IRC server. It's displayed in the UI as a direct message with a user.

**Comment by Jay2k1** [comment]
My point still stands. When I do `/msg irc.libera.chat test` (assuming that is what you mean with "name of the IRC server") I get the same message:

<img width="658" alt="image" src="https://github.com/user-attachments/assets/0a28fa1d-7e56-4852-868c-21a9456c04bf">

I tried that on our demo, https://demo.thelounge.chat. I don't know why that shouldn't work for you. Things you enter in the lobby should be sent to the server if prefixed with a slash. You could try it by typing `/ping`.

**Comment by fl0wfr** [comment]
Below are my commands set in TheLounge (let's say my IRC server is myircserver.com):
`/identify mynickname mypassword
/timer 5 /msg MyIRCServer .invite myhash #channel1 #channel2 #channel3
/timer 10 /away Work`
Timer is managed using thelounge-plugin-timer plugin

**Comment by Jay2k1** [comment]
Probably an issue with the timer plugin, have you tried it without using /timer?

**Comment by brunnre8** [comment]
Take it to our IRC channel please. This is a tracker for packaging problems with the container.
