### ISSUE TITLE
XHR poll error running TheLounge with TLS certificate on QNAP NAS

### ISSUE THREAD

**Issue by wiligl** [thelounge/thelounge-docker#193]
Hi, I get an XHR poll error when I run thelounge/thelounge:latest as a docker container on my QNAP NAS (QTS 5.2.2.2950) connecting from my Linux Pop!OS 22.04 LTS  using Firefox browser (V1133.03) when the config.js contains these settings:

    https: {
        enable: true,
        key: "/var/opt/thelounge/certs/aeree.net/privkey1.pem",
        certificate: "/var/opt/thelounge/certs/aeree.net/fullchain1.pem"
    //  ,  ca: "",
    },

After receiving the XHR poll error and a login page of thelounge, on which the layout looks messed up (like the css were not found), reloading the page in the browser gives the mesage that the browser "cannot connect".

Setting "enable: false" results in thelounge and inspircd server work fine again, ie ignoring the TLS certificate for TheLounge. The same TLS certificate works fine with the inspircd server. 

The concerned domain is aeree.net:9000 (thelounge) and aeree.net:6697 (IRC).

**Comment by brunnre8** [comment]
this is not a docket packaging bug

**Comment by wiligl** [comment]
It seems the issues were caused by and unstable connection to server or server limitations, leading to various errors eg,
1) Browser: XHR poll error (see initial issue)
2) TheLounge: Service worker failed to fetch an url: Failed to fetch
3) IRCD (in TheLounge): *** Connection closed unexpectedly: Error: connect ECONNREFUSED <ip>:6697
