### ISSUE TITLE
Outbound IP

### ISSUE THREAD

**Issue by chasgames** [thelounge/thelounge-docker#33]
How do i set the outbound public IP address?

For example if i bind lounge to 1.1.1.1:80:9000, i can access lounge successfully on http://1.1.1.1

but when i connect to an IRC server, it can choose any interface on my box, so i can connect as 1.1.1.1, 2.2.2.2 or 3.3.3.3. I'm guessing its something to do with docker default gateway..

Thanks, btw great docker!

**Comment by xPaw** [comment]
You can change outgoing bind ip in The Lounge config: https://thelounge.chat/docs/configuration#bind

You will likely need to configure docker network stuff yourself though.
