### ISSUE TITLE
Deprecated?

### ISSUE THREAD

**Issue by mijndert** [thelounge/thelounge-docker#50]
In the README for this repository you tell us to pull thelounge/lounge:latest.

This page tells me thelounge/lounge is deprecated https://hub.docker.com/r/thelounge/lounge/ and we should use https://hub.docker.com/r/thelounge/thelounge/ instead.

In the documentation for the new one you tell us to pull latest, but latest is not a valid tag there and only the development build is available.

Can you clarify which build is actually the one to use?

**Comment by MiniDigger** [comment]
with 3.0, the name has been changed to `thelounge` everywhere. as 3.0 isn't released yet, there is no latest tag for `thelounge`. If you don't want to run prereleases (which generally are considered stable), its just fine to the `lounge:latest` to get the 2.7.1 version. once 3.0 is released however, you should switch over to `thelounge`.

**Comment by mijndert** [comment]
Thanks for the clarification.

I do think this should be more clear in the README though.

**Comment by mijndert** [comment]
@williamboman this works! Thank you very much.
