### ISSUE TITLE
Nicknames are not correctly saved

### ISSUE THREAD

**Issue by 8549** [thelounge/thelounge-docker#90]
I'm running TheLounge via the official Docker container. Whenever TheLounge tries to reconnect to my saved networks (maybe after a container restart or a system reboot, or just after a random network disconnection) it adds a random character to my nicknames and the networks reject my login. I edit the network configuration, save the new nick and click connect: TheLounge has added again a character to my nickname, so that my login fails again.

**Comment by xPaw** [comment]
TL will attempt to get your nickname back if it sees the original nick quit.

In latest pre-release you can configure SASL correctly so it can login even if your nick differs.
