### ISSUE TITLE
Minor https problem with docs (using docker)

### ISSUE THREAD

**Issue by SleepyMario** [thelounge/thelounge-docker#93]
Hello, it seems that with the docker installation it's necessary to set https to true and add a key + certificate in the config.js when using docker (I'm using the Alpine version, which probably doesn't matter) (not mentioned in the reversed proxy part and given as not needed in the config.js).

I know it's possible to do a pull request and stuff but my apologies, I'm not very good at github, hence me posting the issue here. Thanks for all your work :-)

**Comment by xPaw** [comment]
Solved in IRC.

The issue was having `https` in `proxy_pass https://127.0.0.1:9001`.
