### ISSUE TITLE
Prebuilt container appears to be x86 only, add instructions for ARM

### ISSUE THREAD

**Issue by myself248** [thelounge/thelounge-docker#99]
When trying to launch the container on Raspberry Pi, the logs were showing

> standard_init_linux.go:211: exec user process caused "exec format error"

and nothing was listening on port 9000. The helpful folks on IRC diagnosed it as 

> \<halkeye\> myself: ah, i feel like your running a non arm docker image on an arm host

and suggested  

> \<halkeye\> checkout https://github.com/thelounge/thelounge-docker, then run `docker build -t $whateveryouwantforname .`
> \<halkeye\> then swap out thelounge/thelounge in the docker run
> 

And this worked flawlessly. Took almost 40 minutes to build on a raspberry pi 3b, but it did eventually build! So I think the instructions in https://hub.docker.com/r/thelounge/thelounge/ and https://thelounge.chat/docs/install-and-upgrade could be updated with a note to this effect for ARM users. Thank you!

**Comment by xPaw** [comment]
We use docker automated builds, and I think it would be possible to setup and automatic builds for ARM architecture.

Probably just requires copying the dockerfile and changing the base image to a specific arm variant? I'm not sure.

**Comment by klausenbusk** [comment]
> We use docker automated builds, and I think it would be possible to setup and automatic builds for ARM architecture.

The easiest is probably using [buildx](https://github.com/docker/buildx), but that would probably require switching CI (ex: Github Actions). What are your opinion regard switching to ex: Github Actions?

**Comment by xPaw** [comment]
> What are your opinion regard switching to ex: Github Actions?

We do use github actions.

Are you willing to give this a try?

**Comment by klausenbusk** [comment]
> Are you willing to give this a try?

Sure. I assume [automated builds](https://docs.docker.com/docker-hub/builds/) is used at the moment? I think it would be easier to push the image to [GitHub Packages](https://github.com/features/packages). Do you have any strong opinions? We can also push to both.

**Comment by xPaw** [comment]
> I assume automated builds is used at the moment? 

I believe so.

> Do you have any strong opinions? We can also push to both.

Pushing to docker hub is probably easier for users in the end so they don't have to configure a separate source.

**Comment by klausenbusk** [comment]
> Pushing to docker hub is probably easier for users in the end so they don't have to configure a separate source.

The only difference is `docker pull docker.pkg.github.com/thelounge/thelounge/thelounge:4.1.0` vs `docker pull thelounge/thelounge:4.1.0`. The first command is indeed a bit longer. Nevertheless pushing to Docker Hub should be easy to implement.

**Comment by klausenbusk** [comment]
PR opened: #109 

I would be grateful if someone could test the image: `docker pull klausenbusk/thelounge-docker:99.99.99` (should be available in ~10 min) or `docker pull klausenbusk/thelounge-docker:99.99.99-alpine`

**Comment by williamboman** [comment]
Looks like ARM builds are back on the menu. Thanks @klausenbusk!
